# RAG Re-Ranking


In [ ]:
#Defining the source document 
documents = [
    "This is a list which containing sample documents.",
    "Keywords are important for keyword-based search.",
    "Document analysis involves extracting keywords.",
    "Keyword-based search relies on sparse embeddings.",
    "Understanding document structure aids in keyword extraction.",
    "Efficient keyword extraction enhances search accuracy.",
    "Semantic similarity improves document retrieval performance.",
    "Machine learning algorithms can optimize keyword extraction methods."
]

In [4]:
#length of the document
len(documents)

8

In [3]:
#Use Sentence Transformer 
from sentence_transformers import SentenceTransformer
#load the model 
model_name = 'sentence-transformers/paraphrase-xlm-r-multilingual-v1'
#Build the model 
model = SentenceTransformer(model_name)

In [5]:
#Embedding the input document
document_embeddings = model.encode(documents)
len(document_embeddings)

8

In [6]:
#Checking the first value
document_embeddings[0]

array([ 0.10894687,  0.07812068,  0.11626568, -0.31912518,  0.46890223,
        0.43514383,  0.0145374 ,  0.44238767,  0.29716387, -0.18982698,
        0.07389051, -0.27864903,  0.21338157, -0.12077003,  0.17891698,
       -0.00789889,  0.04754862, -0.1820457 ,  0.3422711 , -0.06994268,
       -0.14288744,  0.57141256, -0.1115324 , -0.17895396,  0.0152313 ,
        0.26105705, -0.20555831,  0.05203114, -0.02810781,  0.23873252,
        0.01206981,  0.04404929,  0.02242319, -0.13895173, -0.7410038 ,
        0.2560101 ,  0.08149686,  0.18820496, -0.4123768 ,  0.11368629,
        0.28121153,  0.05860877, -0.17318773,  0.33549127,  0.21803688,
       -0.05090723, -0.05457797, -0.8738478 , -0.24082261,  0.3200697 ,
        0.4476166 ,  0.06347843,  0.53574854,  0.16607259, -0.33197   ,
        0.33393642,  0.28615916, -0.54195666, -0.27132413,  0.24881148,
       -0.23919368, -0.46926293,  0.13836575,  0.37842894, -0.01304437,
        0.01990606,  0.32365087,  0.45857534,  0.07600266,  0.25

In [7]:
#Rechecking the dimension of the embedding
len(document_embeddings[0])

768

In [8]:
#Modifying the output format in a document format 
for i, embedding in enumerate(document_embeddings):
    print(f"Document {i+1} embedding: {embedding}")

Document 1 embedding: [ 0.10894687  0.07812068  0.11626568 -0.31912518  0.46890223  0.43514383
  0.0145374   0.44238767  0.29716387 -0.18982698  0.07389051 -0.27864903
  0.21338157 -0.12077003  0.17891698 -0.00789889  0.04754862 -0.1820457
  0.3422711  -0.06994268 -0.14288744  0.57141256 -0.1115324  -0.17895396
  0.0152313   0.26105705 -0.20555831  0.05203114 -0.02810781  0.23873252
  0.01206981  0.04404929  0.02242319 -0.13895173 -0.7410038   0.2560101
  0.08149686  0.18820496 -0.4123768   0.11368629  0.28121153  0.05860877
 -0.17318773  0.33549127  0.21803688 -0.05090723 -0.05457797 -0.8738478
 -0.24082261  0.3200697   0.4476166   0.06347843  0.53574854  0.16607259
 -0.33197     0.33393642  0.28615916 -0.54195666 -0.27132413  0.24881148
 -0.23919368 -0.46926293  0.13836575  0.37842894 -0.01304437  0.01990606
  0.32365087  0.45857534  0.07600266  0.2529959  -0.42938936  0.10051929
 -0.33042595 -0.69876456  0.01035893  0.05666564  0.1473124  -0.47082344
  0.08063991  0.3387045  -0.2727

In [9]:
#Defining the query 
query = "Natural language processing techniques enhance keyword extraction efficiency."

#Performing Embedding on the query 
query_embedding = model.encode(query)

print("Query Embedding:", query_embedding)

Query Embedding: [ 3.42821062e-01  3.26170474e-01  7.73253338e-03  1.60758775e-02
  2.38517039e-02 -2.52880841e-01  8.15468729e-02  1.37177363e-01
  3.33291799e-01  3.65743861e-02 -9.28223506e-02 -3.43725681e-01
  7.12015927e-02  9.48833823e-01 -9.41290110e-02 -7.96413839e-01
 -3.20592105e-01 -2.67564505e-01  2.08664209e-01  7.99598843e-02
  7.93330837e-03 -5.22297807e-02 -1.00512728e-01 -2.04229757e-01
  2.19562620e-01  7.67739266e-02  1.25881523e-01  2.90843785e-01
 -4.99191105e-01  2.27709621e-01 -1.94742575e-01  7.21394643e-02
 -4.56513371e-03  1.21945575e-01 -1.46225691e-01 -9.64745134e-02
  1.02258235e-01 -2.04421118e-01 -3.95657718e-01  7.32251257e-02
  1.10104166e-01  4.84611154e-01  1.04519255e-01  3.86131734e-01
 -1.68697253e-01 -2.11251125e-01 -6.38036430e-01 -4.32641476e-01
  2.74459153e-01  9.64053422e-02 -1.30053520e-01  5.76568581e-02
  8.07963088e-02  6.48147315e-02 -2.14186427e-03  2.29773819e-01
 -6.66054413e-02  3.07675302e-01  2.11779609e-01 -1.57844469e-01
  9.7886

In [11]:
#Performing Cosine Simillarity between Document Embedding and input query 
import numpy as np 
from sklearn.metrics.pairwise import cosine_similarity

#Perform the simillarity operation
simillarities = cosine_similarity(np.array([query_embedding]), document_embeddings)

In [12]:
#Checking the simillarity score 
simillarities

array([[0.1694815 , 0.4580227 , 0.5675694 , 0.44123286, 0.63161176,
        0.75214124, 0.550352  , 0.74481654]], dtype=float32)

In [14]:
#Identifying the most simillar record
most_simillar_index = np.argmax(simillarities)
print(most_simillar_index)

5


In [16]:
#Displaying the most simillar record 
most_simillar_document = documents[most_simillar_index]
print(most_simillar_document)

Efficient keyword extraction enhances search accuracy.


In [21]:
#similarity score associated to above 
simillarities[0][most_simillar_index]

np.float32(0.75214124)

In [24]:
#Arranging the index in thr order of simillarity in desc 
sorted_indices = np.argsort(simillarities[0])[::-1]
sorted_indices

array([5, 7, 4, 2, 6, 1, 3, 0])

In [25]:
#ranked documents
ranked_docs = [ (documents[i], simillarities[0][i]) for i in sorted_indices]
ranked_docs

[('Efficient keyword extraction enhances search accuracy.',
  np.float32(0.75214124)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float32(0.74481654)),
 ('Understanding document structure aids in keyword extraction.',
  np.float32(0.63161176)),
 ('Document analysis involves extracting keywords.', np.float32(0.5675694)),
 ('Semantic similarity improves document retrieval performance.',
  np.float32(0.550352)),
 ('Keywords are important for keyword-based search.', np.float32(0.4580227)),
 ('Keyword-based search relies on sparse embeddings.', np.float32(0.44123286)),
 ('This is a list which containing sample documents.', np.float32(0.1694815))]

In [26]:
print("Ranked Documents: ")

for rank, (document, simillarity) in enumerate(ranked_docs, start=1):
    print(f"Rank {rank}: Document - {document}, Similarity Score - {simillarity}")

Ranked Documents: 
Rank 1: Document - Efficient keyword extraction enhances search accuracy., Similarity Score - 0.7521412372589111
Rank 2: Document - Machine learning algorithms can optimize keyword extraction methods., Similarity Score - 0.7448165416717529
Rank 3: Document - Understanding document structure aids in keyword extraction., Similarity Score - 0.6316117644309998
Rank 4: Document - Document analysis involves extracting keywords., Similarity Score - 0.567569375038147
Rank 5: Document - Semantic similarity improves document retrieval performance., Similarity Score - 0.5503519773483276
Rank 6: Document - Keywords are important for keyword-based search., Similarity Score - 0.45802271366119385
Rank 7: Document - Keyword-based search relies on sparse embeddings., Similarity Score - 0.4412328600883484
Rank 8: Document - This is a list which containing sample documents., Similarity Score - 0.16948150098323822


In [27]:
print("Top 4 documents")
for rank, (document, simillarity) in enumerate(ranked_docs[:4], start=1):
    print(f"Rank {rank}: Document - {document}, Similarity Score - {simillarity}")


Top 4 documents
Rank 1: Document - Efficient keyword extraction enhances search accuracy., Similarity Score - 0.7521412372589111
Rank 2: Document - Machine learning algorithms can optimize keyword extraction methods., Similarity Score - 0.7448165416717529
Rank 3: Document - Understanding document structure aids in keyword extraction., Similarity Score - 0.6316117644309998
Rank 4: Document - Document analysis involves extracting keywords., Similarity Score - 0.567569375038147


BM25Okapi, often simply referred to as BM25, is a ranking function used by search engines and information retrieval systems to estimate the relevance of documents to a given search query.

In [28]:
#Importing BM25 
from rank_bm25 import BM25Okapi

top_4_documents = [ doc[0] for doc in ranked_docs[:4]]

print(top_4_documents)


['Efficient keyword extraction enhances search accuracy.', 'Machine learning algorithms can optimize keyword extraction methods.', 'Understanding document structure aids in keyword extraction.', 'Document analysis involves extracting keywords.']


In [29]:
#Tokenizing the document 
tokenized_top_4_documents = [doc.split() for doc in top_4_documents]
print(tokenized_top_4_documents)

[['Efficient', 'keyword', 'extraction', 'enhances', 'search', 'accuracy.'], ['Machine', 'learning', 'algorithms', 'can', 'optimize', 'keyword', 'extraction', 'methods.'], ['Understanding', 'document', 'structure', 'aids', 'in', 'keyword', 'extraction.'], ['Document', 'analysis', 'involves', 'extracting', 'keywords.']]


In [31]:
#Tokenising the input query 
tokenized_query = query.split()
print(tokenized_query)

['Natural', 'language', 'processing', 'techniques', 'enhance', 'keyword', 'extraction', 'efficiency.']


In [32]:
#Instantiating BM25
bm25 = BM25Okapi(tokenized_top_4_documents)
print(bm25)

In [34]:
#Getting BM25 score
bm25_score = bm25.get_scores(tokenized_query)
print(bm25_score)

[0.1907998  0.16686672 0.17803252 0.        ]


In [35]:
#Sorting the indices based on arg value 
sorted_indices2 = np.argsort(bm25_score)[::-1]
print(sorted_indices2)

[0 2 1 3]


In [36]:
#Original top 4 documents were
top_4_documents

['Efficient keyword extraction enhances search accuracy.',
 'Machine learning algorithms can optimize keyword extraction methods.',
 'Understanding document structure aids in keyword extraction.',
 'Document analysis involves extracting keywords.']

In [39]:
#Reranked documents
reranked_documents = [(top_4_documents[i], bm25_score[i]) for i in sorted_indices2]
print(reranked_documents)

[('Efficient keyword extraction enhances search accuracy.', np.float64(0.19079979534096053)), ('Understanding document structure aids in keyword extraction.', np.float64(0.1780325227902643)), ('Machine learning algorithms can optimize keyword extraction methods.', np.float64(0.1668667199671815)), ('Document analysis involves extracting keywords.', np.float64(0.0))]


In [40]:
print("Rerank of top 4 Documents:")
for rank, (document, similarity) in enumerate(reranked_documents, start=1):
    print(f"Rank {rank}: Document - '{document}', Similarity Score - {similarity}")

Rerank of top 4 Documents:
Rank 1: Document - 'Efficient keyword extraction enhances search accuracy.', Similarity Score - 0.19079979534096053
Rank 2: Document - 'Understanding document structure aids in keyword extraction.', Similarity Score - 0.1780325227902643
Rank 3: Document - 'Machine learning algorithms can optimize keyword extraction methods.', Similarity Score - 0.1668667199671815
Rank 4: Document - 'Document analysis involves extracting keywords.', Similarity Score - 0.0


In [42]:
reranked_documents[:4]

[('Efficient keyword extraction enhances search accuracy.',
  np.float64(0.19079979534096053)),
 ('Understanding document structure aids in keyword extraction.',
  np.float64(0.1780325227902643)),
 ('Machine learning algorithms can optimize keyword extraction methods.',
  np.float64(0.1668667199671815)),
 ('Document analysis involves extracting keywords.', np.float64(0.0))]

# RAG + ReRanking using BM25

In [60]:
# ── 1. imports ──────────────────────────────────────────────────────
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain import hub

import faiss
from rank_bm25 import BM25Okapi
import re, numpy as np

from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnablePassthrough, RunnableLambda

In [61]:
# ── 2. load & chunk the PDF ─────────────────────────────────────────
FILE_PATH = "llama2.pdf"
loader    = PyPDFLoader(FILE_PATH)
pages     = loader.load()

splitter  = RecursiveCharacterTextSplitter(
    chunk_size    = 500,
    chunk_overlap = 50
)
docs = splitter.split_documents(pages)

In [62]:
# ── 3. build FAISS vector store (MiniLM embeddings) ────────────────
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

dim   = len(embeddings.embed_query("dummy text"))   # 384 for MiniLM
index = faiss.IndexFlatIP(dim)

vector_store = FAISS(
    embedding_function   = embeddings,
    index                = index,
    docstore             = InMemoryDocstore(),
    index_to_docstore_id = {}
)
vector_store.add_documents(docs)

['033b1986-d271-468c-9fa7-c126689a1c4d',
 '7397edbc-8a19-4725-8a38-a17462f38c4e',
 '6a1c23b9-d0b7-44fc-9772-9bba234082a6',
 'd11c144f-aecd-4028-bdb5-c26d98bdbf8a',
 '98e9b7ea-8e7a-4d6b-a01c-34648a22e33f',
 '1f6b246d-0052-4b5b-a955-82447709f0ec',
 '0ee32d15-7374-4130-aa2c-29e767a5379d',
 'a45da763-8a18-43bc-aedb-216349a8d2fc',
 '5d1f6e3c-6682-4553-b1a2-cc5154ffdf7a',
 '837d226a-ab3c-44d2-86b2-3a7703e38595',
 '0de8344b-4e68-43a7-b269-ce45836712f2',
 'a2b477bd-f94f-41b7-b45d-60c231aad5d3',
 '6b1e36df-613b-4712-aaad-fad4491c48f1',
 '0f7132f2-3d7c-482d-bb00-566cb6b2497d',
 '9f6ab6b0-3dbc-4fc5-bad3-a037f4ab79d3',
 '44483fcf-922b-4e60-9e55-e1163b7b28eb',
 'b1113ab4-8fb0-4733-a4c6-85bdd47b51cb',
 '4be63223-2f6f-40bd-9681-96aae0c4fbb2',
 'd010985f-0f58-4e7b-9a4e-f8181b052855',
 '31b1ff57-ef11-4743-97c4-09742afe5f42',
 '1a5a7686-8fba-4ada-9ec5-98320dc5d8a4',
 '6ee15185-c14b-4992-949f-28947902d45c',
 'c6dd7ff8-ee5a-4020-9a4d-44bb9f3177f3',
 '2da5b752-80f7-4449-b790-1b29d87399a8',
 'ac085da9-0662-

In [63]:
# ── 4. dense recall retriever (larger pool) ────────────────────────
initial_k       = 20
dense_retriever = vector_store.as_retriever(search_kwargs={"k": initial_k})

In [64]:
# ── 5. BM-25 re-ranker ─────────────────────────────────────────────
def bm25_rerank_fn(inputs: dict, top_k: int = 5):
    """inputs = {"question": str, "docs": List[Document]}"""
    question, candidate_docs = inputs["question"], inputs["docs"]

    tokenize = lambda txt: re.findall(r"\w+", txt.lower())
    corpus   = [tokenize(d.page_content) for d in candidate_docs]

    bm25     = BM25Okapi(corpus)
    scores   = bm25.get_scores(tokenize(question))

    best_idx = np.argsort(scores)[::-1][:top_k]
    return [candidate_docs[i] for i in best_idx]

bm25_reranker = RunnableLambda(bm25_rerank_fn)

In [65]:
# ── 6. prompt, model, helpers ──────────────────────────────────────
prompt     = hub.pull("rlm/rag-prompt")           # classic RAG prompt
model      = ChatGoogleGenerativeAI(model="gemini-1.5-flash")
out_parser = StrOutputParser()

def format_docs(doc_list):
    return "\n\n".join(d.page_content for d in doc_list)

In [66]:
# ── 7. the full RAG chain ──────────────────────────────────────────
rag_chain = (
    {
        "docs":     dense_retriever,        # dense recall
        "question": RunnablePassthrough()
    }
    | bm25_reranker                        # lexical re-rank
    | (lambda d: {"context": format_docs(d), "question": ""})
    | prompt
    | model
    | out_parser
)

In [67]:
# ── 8. test run ────────────────────────────────────────────────────
if __name__ == "__main__":
    query  = "What is a Llama model?"
    answer = rag_chain.invoke(query)
    print(f"Q: {query}\nA: {answer}")

Q: What is a Llama model?
A: Llama 2 is an auto-regressive language model with transformer architecture.  It comes in 7B, 13B, and 70B parameter sizes, with pretrained and fine-tuned variations.  The model was trained between January and July 2023.
